language: generic
branches:
  only:
    - master

before_install:
 - pip install html5validator
 - gem install awesome_bot

script: html5validator --match *.html && awesome_bot index.html --allow-dupe
